// Package codegen emits project-specific Go adapters for Karty UI and assets.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
	"unicode"
)

type staticError string

func (err staticError) Error() string {
	return string(err)
}

const (
	errInvalidAssetName   staticError = "asset name cannot produce a Go identifier"
	errAssetNameCollision staticError = "asset names produce the same Go identifier"
	errReservedAssetName  staticError = "asset names produce a reserved Go identifier"
)

// TextureAssetFile emits typed logical texture references from karty.toml.
func TextureAssetFile(names []string) ([]byte, error) {
	return namedAssetFile(names, "Texture", "TextureID")
}

// UIAssetFile emits typed UI asset names, sharing identifier collision checks.
func UIAssetFile(names []string) ([]byte, error) {
	return namedAssetFile(names, "UI", "UIAsset")
}

// TextureAssetPackageFile emits typed texture references in package assets.
func TextureAssetPackageFile(names []string, engineImport string) ([]byte, error) {
	return namedAssetPackageFile(names, "Texture", "TextureID", engineImport)
}

// UIAssetPackageFile emits typed UI references in package assets.
func UIAssetPackageFile(names []string, engineImport string) ([]byte, error) {
	return namedAssetPackageFile(names, "UI", "UIAsset", engineImport)
}

func namedAssetFile(names []string, prefix, assetType string) ([]byte, error) {
	return namedAssetPackageFile(names, prefix, assetType, "")
}

func namedAssetPackageFile(names []string, prefix, assetType, engineImport string) ([]byte, error) {
	type texture struct {
		Name       string
		Identifier string
	}

	textures := make([]texture, 0, len(names))

	identifiers := make(map[string]string, len(names))
	for _, name := range names {
		identifier := prefix + strings.TrimPrefix(textureIdentifier(name), "Texture")
		if identifier == prefix {
			return nil, fmt.Errorf("%q: %w", name, errInvalidAssetName)
		}

		if identifier == assetType || identifier == "UIElement" || identifier == "UIAction" || identifier == "UIRow" {
			return nil, fmt.Errorf("%q -> %s: %w", name, identifier, errReservedAssetName)
		}

		if previous, exists := identifiers[identifier]; exists {
			return nil, fmt.Errorf("%q and %q -> %s: %w", previous, name, identifier, errAssetNameCollision)
		}

		identifiers[identifier] = name
		textures = append(textures, texture{Name: name, Identifier: identifier})
	}

	data := struct {
		GeneratedComment string
		Textures         []texture
		AssetType        string
		Package          string
		EngineImport     string
		Qualifier        string
	}{
		GeneratedComment: "// Code generated by Karty. DO NOT EDIT.\n" +
			"// WARNING: DO NOT MODIFY THIS FILE DIRECTLY.\n" +
			"// WARNING: MANUAL CHANGES WILL BE OVERWRITTEN.\n" +
			"// Source of truth: karty.toml and karty-ui/codegen/templates/assets.go.tmpl.\n" +
			"// Change the asset declarations or generator, then run karty build.\n" +
			"// Regenerate with: karty build\n\n",
		Textures:  textures,
		AssetType: assetType,
		Package:   "engine",
	}
	if engineImport != "" {
		data.Package = "assets"
		data.EngineImport = engineImport
		data.Qualifier = "engine."
	}

	parsed, err := template.New("engine/assets.go").Parse(assetsSourceTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse engine/assets.go: %w", err)
	}

	var output bytes.Buffer
	if err := parsed.Execute(&output, data); err != nil {
		return nil, fmt.Errorf("render engine/assets.go: %w", err)
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format engine/assets.go: %w", err)
	}

	return formatted, nil
}

func textureIdentifier(name string) string {
	identifier := strings.Builder{}
	identifier.WriteString("Texture")

	upper := true

	for _, character := range name {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			upper = true

			continue
		}

		if upper {
			character = unicode.ToUpper(character)
			upper = false
		}

		identifier.WriteRune(character)
	}

	return identifier.String()
}
